name: Feature Build Test

on:
 push:
   branches: [feature/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'

      - name: Install & Build
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
